apiVersion: v1
kind: Service
metadata:
  name: {{ include "ashim.fullname" . }}
  namespace: {{ include "ashim.namespace" . }}
  labels:
    {{- include "ashim.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ashim.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 1349
      protocol: TCP
